-- 코드를 작성해주세요
SELECT COUNT(I.ID) AS FISH_COUNT
FROM FISH_INFO I, FISH_NAME_INFO N
WHERE I.FISH_TYPE = N.FISH_TYPE
AND I.FISH_TYPE IN (SELECT FISH_TYPE FROM FISH_NAME_INFO 
                    WHERE FISH_NAME IN ('BASS','SNAPPER'))
